# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Floppy"
license = "GPL-2.0"
licenselink = "https://github.com/nardoyala/hugo-floppy/blob/master/LICENSE.md"
description = "Floppy is a blog theme for Hugo that focuses on your content."
homepage = "https://github.com/nardoyala/hugo-floppy"
tags = ["modern", "minimal", "clean", "blog", "responsive", "personal", "simple", "minimalist"]
features = ["Blog", "Modern", "Minimal", "Responsive", "Social media links", "Syntax highlighting"]
min_version = "0.67.1"

[author]
  name = "Bernardo Ayala"
  homepage = "https://bernardoayala.com"

[original]
    author = "Benedikt 'dataCobra' Tuchen"
    homepage = "https://thinkbot.de"
    repo = "https://github.com/dataCobra/hugo-vitae"
