baseURL = "http://example.org/"
languageCode = "en-us"
title = "Floppy"
theme = "hugo-floppy"
paginate = 100

copyright = "© Copyright notice | [Vitae](https://github.com/dataCobra/hugo-vitae) theme for [Hugo](https://gohugo.io)"

googleAnalytics = "UA-123-45"

[permalinks]
  posts = "/:slug/"
  pages = "/:title/"
  categories = "/:title/"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe= true

[taxonomies]
	tag = "tags"
	series = "series"
  category = "categories"

[params]
	subtitle = "A minimalistic blog theme for Hugo"

  favicon = "/img/icons/floppy.png"

	# Optional 48x48 header icon icon.
	headerIcon = "/img/icons/floppy.png"

  # Profile picture
  profilePicture = "/img/profilePicture.jpg"

  # Greeting message
  greetingMessage = "Greetins, human"

  # Small about me
  about = "This text here says information about me. It's like a small bio."

	# Custom CSS applied to default styles.
	customCSS = "css/custom.css"

  description = "A minimalistic blog theme for Hugo"

# Nav.

[[menu.main]]
name = "About"
url = "/about"
weight = 1

[[menu.main]]
name = "Contact"
url = "/contact"
weight = 2

# List of tools used to build the page
[[params.tools]]
  name = "Hugo"
  title = "Built with HUGO"
  icon = "/img/icons/hugo.png"
  url = "https://gohugo.io/"

[[params.tools]]
  name = "icons8"
  title = "Icons from icons8"
  icon = "/img/icons/icons8.png"
  url = "https://icons8.com/"

[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/"

[[params.social]]
name = "Twitter"
icon = "fab fa-twitter"
url = "https://twitter.com/"

[[params.social]]
name = "Instagram"
icon = "fab fa-instagram"
url = "https://instagram.com/"
